### ISSUE TITLE
Issue with Integrating with Spring Boot 2.4.x

### ISSUE THREAD

**Issue by shortthirdman** [lukashinsch/spring-boot-actuator-logview#31]
This is the exception/error when application is built or run using Maven:
`Caused by: java.lang.NoClassDefFoundError: org/springframework/boot/actuate/endpoint/mvc/MvcEndpoint
        at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.8.0_291]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[na:1.8.0_291]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[na:1.8.0_291]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468) ~[na:1.8.0_291]
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74) ~[na:1.8.0_291]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369) ~[na:1.8.0_291]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363) ~[na:1.8.0_291]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_291]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362) ~[na:1.8.0_291]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[na:1.8.0_291]
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355) ~[na:1.8.0_291]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[na:1.8.0_291]
        at java.lang.Class.getDeclaredMethods0(Native Method) ~[na:1.8.0_291]
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[na:1.8.0_291]
        at java.lang.Class.getDeclaredMethods(Class.java:1975) ~[na:1.8.0_291]
        at org.springframework.cglib.core.ReflectUtils.addAllMethods(ReflectUtils.java:451) ~[spring-core-5.3.7.jar:5.3.7]
        at org.springframework.cglib.proxy.Enhancer.getMethods(Enhancer.java:635) ~[spring-core-5.3.7.jar:5.3.7]
        at org.springframework.cglib.proxy.Enhancer.generateClass(Enhancer.java:670) ~[spring-core-5.3.7.jar:5.3.7]
        at org.springframework.cglib.transform.TransformingClassGenerator.generateClass(TransformingClassGenerator.java:33) ~[spring-core-5.3.7.jar:5.3.7]
        at org.springframework.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25) ~[spring-core-5.3.7.jar:5.3.7]
        at org.springframework.cglib.core.ClassLoaderAwareGeneratorStrategy.generate(ClassLoaderAwareGeneratorStrategy.java:57) ~[spring-core-5.3.7.jar:5.3.7]
        at org.springframework.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:358) ~[spring-core-5.3.7.jar:5.3.7]
        at org.springframework.cglib.proxy.Enhancer.generate(Enhancer.java:585) ~[spring-core-5.3.7.jar:5.3.7]
        at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:110) ~[spring-core-5.3.7.jar:5.3.7]
        at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:108) ~[spring-core-5.3.7.jar:5.3.7]
        at org.springframework.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54) ~[spring-core-5.3.7.jar:5.3.7]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_291]
        at org.springframework.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:61) ~[spring-core-5.3.7.jar:5.3.7]
        ... 26 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.actuate.endpoint.mvc.MvcEndpoint
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[na:1.8.0_291]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[na:1.8.0_291]
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355) ~[na:1.8.0_291]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[na:1.8.0_291]
        ... 54 common frames omitted`

**Comment by shortthirdman** [comment]
This is the environment used:

Spring Boot 2.4.6
Maven 3.8.6
Java SDK 1.8
Library version: 0.2.13

@oyvindhorneland @lukashinsch Please help in rectifying the issue or atleast where I am going wrong.

**Comment by lukashinsch** [comment]
Unfortunately, this (old) project uses spring boot 1.x, and in 2.x there were breaking changes regarding the actuator infrastructure. Sorry to disappoint you.

**Comment by shortthirdman** [comment]
Any intentions on developing that for Spring Boot 2.x.x? @lukashinsch
